### ISSUE TITLE
Could not save or export database

### ISSUE THREAD

**Issue by berceanu** [sztyler/sensordatacollector#1]
Sensor Data Collector 1.5.19
Phone: Oneplus 3 A3000
OS: Android 6.0.1

After collecting some accelerometer data from my phone and then turning off the sensor, I can't save or export the database. In Prererences, 

Save database returns:
```Could not create File!```

Export tables (CSV) and leaving the defaults selected produces:
```Export failed```

On a separate note, could you please tell me where the database is actually located on the phone?

**Comment by sztyler** [comment]
This error occurs if there is not internal or external (removable) SD-card. I assume that there is an internal SD-card but was not recognized as such. I will investigate this error.

The database itself should be located in:
//data/data/<Your-Application-Package-Name>/databases/<your-database-name>
(but notice that the regular user does not have access to this path)

**Comment by sztyler** [comment]
I just realized that it is a specific permission problem. It is fixed in 1.5.21.
